spring.application.name=backend
spring.config.import=optional:file:.env[.properties]
# Database configuration
spring.datasource.url=${LOCAL_DB_URL}
spring.datasource.username=${LOCAL_DB_USERNAME}
spring.datasource.password=${LOCAL_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret.string=${JWT_SECRET}
jwt.expiration.time=${JWT_EXPRIRATION_TIME}
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#Enable TLS SMTP MAIL
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
password.reset.link=http://localhost:3000/reset-password?code=
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#aws.config
aws.accessKeyId=${AWS_ACCESS_KEY}
aws.secretAccessKey=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucketName=${AWS_S3_BUCKET_NAME}